enum unicode_names {
    GK_QUES = SAFE_RANGE,
    GK_SS = SAFE_RANGE,
    GK_PH = SAFE_RANGE,
    GK_P = SAFE_RANGE,
    GK_B = SAFE_RANGE,
    GK_XI = SAFE_RANGE,
    GK_L = SAFE_RANGE,
    GK_U = SAFE_RANGE,
    GK_DG = SAFE_RANGE,
    GK_SEMI = SAFE_RANGE,
    GK_A = SAFE_RANGE,
    GK_R = SAFE_RANGE,
    GK_S = SAFE_RANGE,
    GK_T = SAFE_RANGE,
    GK_G = SAFE_RANGE,
    GK_M = SAFE_RANGE,
    GK_N = SAFE_RANGE,
    GK_E = SAFE_RANGE,
    GK_I = SAFE_RANGE,
    GK_O = SAFE_RANGE,
    GK_Z = SAFE_RANGE,
    GK_X = SAFE_RANGE,
    GK_PS = SAFE_RANGE,
    GK_D = SAFE_RANGE,
    GK_OM = SAFE_RANGE,
    GK_K = SAFE_RANGE,
    GK_H = SAFE_RANGE,
    GK_TH = SAFE_RANGE,
    GK_KO = SAFE_RANGE,
    GK_ST = SAFE_RANGE,
};

const uint32_t unicode_map[] PROGMEM = {
    [GK_QUES] = 0x37e, // question
    [GK_SEMI] = 0x0387, // semicolon
    [GK_A_L] = 0x03B1, // alpha lower
	[GK_A_U] = 0x0391, // alpha upper
	[GK_AS_L] = 0x1F00, // alpha smooth lower
	[GK_AS_U] = 0x1F08, // alpha smooth upper
	[GK_ASA_L] = 0x1F04, // alpha smooth acute lower
	[GK_ASA_U] = 0x1F0C, // alpha smooth acute upper
	[GK_ASAI_L] = 0x1F84, // alpha smooth acute iota lower
	[GK_ASAI_U] = 0x1F8C, // alpha smooth acute iota upper
	[GK_ASG_L] = 0x1F02, // alpha smooth grave lower
	[GK_ASG_U] = 0x1F0A, // alpha smooth grave upper
	[GK_ASGI_L] = 0x1F82, // alpha smooth grave iota lower
	[GK_ASGI_U] = 0x1F8A, // alpha smooth grave iota upper
	[GK_ASC_L] = 0x1F06, // alpha smooth circumflex lower
	[GK_ASC_U] = 0x1F0E, // alpha smooth circumflex upper
	[GK_ASCI_L] = 0x1F86, // alpha smooth circumflex iota lower
	[GK_ASCI_U] = 0x1F8E, // alpha smooth circumflex iota upper
	[GK_ASI_L] = 0x1F80, // alpha smooth iota lower
	[GK_ASI_U] = 0x1F88, // alpha smooth iota upper
	[GK_AR_L] = 0x1F01, // alpha rough lower
	[GK_AR_U] = 0x1F09, // alpha rough upper
	[GK_ARA_L] = 0x1F05, // alpha rough acute lower
	[GK_ARA_U] = 0x1F0D, // alpha rough acute upper
	[GK_ARAI_L] = 0x1F85, // alpha rough acute iota lower
	[GK_ARAI_U] = 0x1F8D, // alpha rough acute iota upper
	[GK_ARG_L] = 0x1F03, // alpha rough grave lower
	[GK_ARG_U] = 0x1F0B, // alpha rough grave upper
	[GK_ARGI_L] = 0x1F83, // alpha rough grave iota lower
	[GK_ARGI_U] = 0x1F8B, // alpha rough grave iota upper
	[GK_ARC_L] = 0x1F07, // alpha rough cirumflex lower
	[GK_ARC_U] = 0x1F0F, // alpha rough cirumflex upper
	[GK_ARCI_L] = 0x1F87, // alpha rough cirumflex iota lower
	[GK_ARCI_U] = 0x1F8F, // alpha rough cirumflex iota upper
	[GK_ARI_L] = 0x1F81, // alpha rough iota lower
	[GK_ARI_U] = 0x1F89, // alpha rough iota upper
	[GK_AA_L] = 0x03AC, // alpha acute lower
	[GK_AA_U] = 0x0386, // alpha acute upper
	[GK_AAI_L] = 0x1FB4, // alpha acute iota lower
	[GK_AAI_U] = 0x1FB4, // alpha acute iota upper
	[GK_AG_L] = 0x1F70, // alpha grave lower
	[GK_AG_U] = 0x1FBA, // alpha grave upper
	[GK_AGI_L] = 0x1FB2, // alpha grave iota lower
	[GK_AGI_U] = 0x1FB2, // alpha grave iota upper
	[GK_AB_L] = 0x1FB0, // alpha breve lower
	[GK_AB_U] = 0x1FB8, // alpha breve upper
	[GK_AC_L] = 0x1FB6, // alpha circumflex lower
	[GK_AC_U] = 0x1FB6, // alpha circumflex upper
	[GK_ACI_L] = 0x1FB7, // alpha circumflex iota lower
	[GK_ACI_U] = 0x1FB7, // alpha circumflex iota upper
	[GK_AL_L] = 0x1FB1, // alpha long lower
	[GK_AL_U] = 0x1FB9, // alpha long upper
	[GK_AI_L] = 0x1FB3, // alpha iota lower
	[GK_AI_U] = 0x1FBC, // alpha iota upper
	[GK_B_L] = 0x03B2, // beta lower
	[GK_B_U] = 0x0392, // beta upper
	[GK_G_L] = 0x03B3, // gamma lower
	[GK_G_U] = 0x0393, // gamma upper
	[GK_D_L] = 0x03B4, // delta lower
	[GK_D_U] = 0x0394, // delta upper
	[GK_E_L] = 0x03F5, // epsilon lower
	[GK_E_U] = 0x0395, // epsilon upper
	[GK_ES_L] = 0x1F10, // epsilon smooth lower
	[GK_ES_U] = 0x1F18, // epsilon smooth upper
	[GK_ESA_L] = 0x1F14, // epsilon smooth acute lower
	[GK_ESA_U] = 0x1F1C, // epsilon smooth acute upper
	[GK_ESG_L] = 0x1F12, // epsilon smooth grave lower
	[GK_ESG_U] = 0x1F1A, // epsilon smooth grave upper
	[GK_ER_L] = 0x1F11, // epsilon rough lower
	[GK_ER_U] = 0x1F19, // epsilon rough upper
	[GK_ERA_L] = 0x1F15, // epsilon rough acute lower
	[GK_ERA_U] = 0x1F1D, // epsilon rough acute upper
	[GK_ERG_L] = 0x1F13, // epsilon rough grave lower
	[GK_ERG_U] = 0x1F1B, // epsilon rough grave upper
	[GK_EA_L] = 0x1F73, // epsilon acute lower
	[GK_EA_U] = 0x1FC9, // epsilon acute upper
	[GK_EG_L] = 0x1F72, // epsilon grave lower
	[GK_EG_U] = 0x1FC8, // epsilon grave upper
	[GK_Z_L] = 0x03B6, // zeta lower
	[GK_Z_U] = 0x0396, // zeta upper
	[GK_H_L] = 0x03B7, // eta lower
	[GK_H_U] = 0x0397, // eta upper
	[GK_HS_L] = 0x1F20, // eta smooth lower
	[GK_HS_U] = 0x1F28, // eta smooth upper
	[GK_HSA_L] = 0x1F24, // eta smooth acute lower
	[GK_HSA_U] = 0x1F2C, // eta smooth acute upper
	[GK_HSAI_L] = 0x1F94, // eta smooth acute iota lower
	[GK_HSAI_U] = 0x1F9C, // eta smooth acute iota upper
	[GK_HSG_L] = 0x1F22, // eta smooth grave lower
	[GK_HSG_U] = 0x1F2A, // eta smooth grave upper
	[GK_HSGI_L] = 0x1F92, // eta smooth grave iota lower
	[GK_HSGI_U] = 0x1F9A, // eta smooth grave iota upper
	[GK_HSC_L] = 0x1F26, // eta smooth circumflex lower
	[GK_HSC_U] = 0x1F2E, // eta smooth circumflex upper
	[GK_HSCI_L] = 0x1F96, // eta smooth circumflex iota lower
	[GK_HSCI_U] = 0x1F9E, // eta smooth circumflex iota upper
	[GK_HSI_L] = 0x1F90, // eta smooth iota lower
	[GK_HSI_U] = 0x1F98, // eta smooth iota upper
	[GK_HR_L] = 0x1F21, // eta rough lower
	[GK_HR_U] = 0x1F29, // eta rough upper
	[GK_HRA_L] = 0x1F25, // eta rough acute lower
	[GK_HRA_U] = 0x1F2D, // eta rough acute upper
	[GK_HRAI_L] = 0x1F95, // eta rough acute iota lower
	[GK_HRAI_U] = 0x1F9D, // eta rough acute iota upper
	[GK_HRG_L] = 0x1F23, // eta rough grave lower
	[GK_HRG_U] = 0x1F2B, // eta rough grave upper
	[GK_HRGI_L] = 0x1F93, // eta rough grave iota lower
	[GK_HRGI_U] = 0x1F9B, // eta rough grave iota upper
	[GK_HRC_L] = 0x1F27, // eta rough cirumflex lower
	[GK_HRC_U] = 0x1F2F, // eta rough cirumflex upper
	[GK_HRCI_L] = 0x1F97, // eta rough cirumflex iota lower
	[GK_HRCI_U] = 0x1F9F, // eta rough cirumflex iota upper
	[GK_HRI_L] = 0x1F91, // eta rough iota lower
	[GK_HRI_U] = 0x1F99, // eta rough iota upper
	[GK_HA_L] = 0x1F75, // eta acute lower
	[GK_HA_U] = 0x1FCB, // eta acute upper
	[GK_HAI_L] = 0x1FC4, // eta acute iota lower
	[GK_HAI_U] = 0x1FC4, // eta acute iota upper
	[GK_HG_L] = 0x1F74, // eta grave lower
	[GK_HG_U] = 0x1FCA, // eta grave upper
	[GK_HGI_L] = 0x1FC2, // eta grave iota lower
	[GK_HGI_U] = 0x1FC2, // eta grave iota upper
	[GK_HC_L] = 0x1FC6, // eta circumflex lower
	[GK_HC_U] = 0x1FC6, // eta circumflex upper
	[GK_HCI_L] = 0x1FC7, // eta circumflex iota lower
	[GK_HCI_U] = 0x1FC7, // eta circumflex iota upper
	[GK_HI_L] = 0x1FC3, // eta iota lower
	[GK_HI_U] = 0x1FCC, // eta iota upper
	[GK_TH_L] = 0x03B8, // theta lower
	[GK_TH_U] = 0x0398, // theta upper
	[GK_I_L] = 0x03B9, // iota lower
	[GK_I_U] = 0x0399, // iota upper
	[GK_IS_L] = 0x1F30, // iota smooth lower
	[GK_IS_U] = 0x1F38, // iota smooth upper
	[GK_ISA_L] = 0x1F34, // iota smooth acute lower
	[GK_ISA_U] = 0x1F3C, // iota smooth acute upper
	[GK_ISG_L] = 0x1F32, // iota smooth grave lower
	[GK_ISG_U] = 0x1F3A, // iota smooth grave upper
	[GK_ISC_L] = 0x1F36, // iota smooth circumflex lower
	[GK_ISC_U] = 0x1F3E, // iota smooth circumflex upper
	[GK_IR_L] = 0x1F31, // iota rough lower
	[GK_IR_U] = 0x1F39, // iota rough upper
	[GK_IRA_L] = 0x1F35, // iota rough acute lower
	[GK_IRA_U] = 0x1F3D, // iota rough acute upper
	[GK_IRG_L] = 0x1F33, // iota rough grave - lower
	[GK_IRG_U] = 0x1F3B, // iota rough grave - upper
	[GK_IRC_L] = 0x1F37, // iota rough circumflex lower
	[GK_IRC_U] = 0x1F3F, // iota rough circumflex upper
	[GK_IA_L] = 0x1F77, // iota acute lower
	[GK_IA_U] = 0x1FDB, // iota acute upper
	[GK_IG_L] = 0x1F76, // iota grave lower
	[GK_IG_U] = 0x1FDA, // iota grave upper
	[GK_IB_L] = 0x1FD0, // iota breve lower
	[GK_IB_U] = 0x1FD8, // iota breve upper
	[GK_IC_L] = 0x1FD6, // iota circumflex lower
	[GK_IC_U] = 0x1FD6, // iota circumflex upper
	[GK_ID_L] = 0x03CA, // iota diacritic lower
	[GK_ID_U] = 0x03AA, // iota diacritic upper
	[GK_IDG_L] = 0x1FD3, // iota diacritic grave lower
	[GK_IDG_U] = 0x1FD3, // iota diacritic grave upper
	[GK_IDA_L] = 0x1FD2, // iota diacritic acute lower
	[GK_IDA_U] = 0x1FD2, // iota diacritic acute upper
	[GK_IDC_L] = 0x1FD7, // iota diacritic circumflex lower
	[GK_IDC_U] = 0x1FD7, // iota diacritic circumflex upper
	[GK_IL_L] = 0x1FD1, // iota long lower
	[GK_IL_U] = 0x1FD9, // iota long upper
	[GK_K_L] = 0x03BA, // kappa lower
	[GK_K_U] = 0x039A, // kappa upper
	[GK_L_L] = 0x03BB, // lambda lower
	[GK_L_U] = 0x039B, // lambda upper
	[GK_M_L] = 0x03BC, // mu lower
	[GK_M_U] = 0x039C, // mu upper
	[GK_N_L] = 0x03BD, // nu lower
	[GK_N_U] = 0x039D, // nu upper
	[GK_XI_L] = 0x03BE, // xi lower
	[GK_XI_U] = 0x039E, // xi upper
	[GK_O_L] = 0x03BF, // omicron lower
	[GK_O_U] = 0x039F, // omicron upper
	[GK_OS_L] = 0x1F40, // omicron smooth lower
	[GK_OS_U] = 0x1F48, // omicron smooth upper
	[GK_OSA_L] = 0x1F44, // omicron smooth acute lower
	[GK_OSA_U] = 0x1F4C, // omicron smooth acute upper
	[GK_OSG_L] = 0x1F42, // omicron smooth grave lower
	[GK_OSG_U] = 0x1F4A, // omicron smooth grave upper
	[GK_OR_L] = 0x1F41, // omicron rough lower
	[GK_OR_U] = 0x1F49, // omicron rough upper
	[GK_ORA_L] = 0x1F45, // omicron rough acute lower
	[GK_ORA_U] = 0x1F4D, // omicron rough acute upper
	[GK_ORG_L] = 0x1F43, // omicron rough grave lower
	[GK_ORG_U] = 0x1F4B, // omicron rough grave upper
	[GK_OA_L] = 0x1F79, // omicron acute lower
	[GK_OA_U] = 0x1FF9, // omicron acute upper
	[GK_OG_L] = 0x1F78, // omicron grave lower
	[GK_OG_U] = 0x1FF8, // omicron grave upper
	[GK_P_L] = 0x03C0, // pi lower
	[GK_P_U] = 0x03A0, // pi upper
	[GK_R_L] = 0x03C1, // ro lower
	[GK_R_U] = 0x03A1, // ro upper
	[GK_S_L] = 0x03C3, // sigma lower
	[GK_S_U] = 0x03A3, // sigma upper
	[GK_SS_L] = 0x03C2, // final sigma lower
	[GK_SS_U] = 0x03A3, // final sigma upper
	[GK_T_L] = 0x03C4, // tau lower
	[GK_T_U] = 0x03A4, // tau upper
	[GK_U_L] = 0x03C5, // upsilon lower
	[GK_U_U] = 0x03A5, // upsilon upper
	[GK_US_L] = 0x1F50, // upsilon smooth lower
	[GK_US_U] = 0x1F50, // upsilon smooth upper
	[GK_USA_L] = 0x1F54, // upsilon smooth acute lower
	[GK_USA_U] = 0x1F54, // upsilon smooth acute upper
	[GK_USG_L] = 0x1F52, // upsilon smooth grave lower
	[GK_USG_U] = 0x1F52, // upsilon smooth grave upper
	[GK_USC_L] = 0x1F56, // upsilon smooth circumflex lower
	[GK_USC_U] = 0x1F56, // upsilon smooth circumflex upper
	[GK_UR_L] = 0x1F51, // upsilon rough lower
	[GK_UR_U] = 0x1F59, // upsilon rough upper
	[GK_URA_L] = 0x1F55, // upsilon rough acute lower
	[GK_URA_U] = 0x1F5D, // upsilon rough acute upper
	[GK_URG_L] = 0x1F53, // upsilon rough grave lower
	[GK_URG_U] = 0x1F5B, // upsilon rough grave upper
	[GK_URC_L] = 0x1F57, // upsilon rough circumflex lower
	[GK_URC_U] = 0x1F5F, // upsilon rough circumflex upper
	[GK_UA_L] = 0x1F7B, // upsilon acute lower
	[GK_UA_U] = 0x1FEB, // upsilon acute upper
	[GK_UG_L] = 0x1F7A, // upsilon grave lower
	[GK_UG_U] = 0x1FEA, // upsilon grave upper
	[GK_UB_L] = 0x1FE0, // upsilon breve lower
	[GK_UB_U] = 0x1FE8, // upsilon breve upper
	[GK_UC_L] = 0x1FE6, // upsilon circumflex lower
	[GK_UC_U] = 0x1FE6, // upsilon circumflex upper
	[GK_UD_L] = 0x03CB, // upsilon diacritic lower
	[GK_UD_U] = 0x03AB, // upsilon diacritic upper
	[GK_UDG_L] = 0x1FE3, // upsilon diacritic grave lower
	[GK_UDG_U] = 0x1FE3, // upsilon diacritic grave upper
	[GK_UDA_L] = 0x1FE2, // upsilon diacritic acute lower
	[GK_UDA_U] = 0x1FE2, // upsilon diacritic acute upper
	[GK_UDC_L] = 0x1FE7, // upsilon diacritic circumflex lower
	[GK_UDC_U] = 0x1FE7, // upsilon diacritic circumflex upper
	[GK_UL_L] = 0x1FE1, // upsilon long lower
	[GK_UL_U] = 0x1FE9, // upsilon long upper
	[GK_PH_L] = 0x03C6, // phi lower
	[GK_PH_U] = 0x03A6, // phi upper
	[GK_X_L] = 0x03C7, // chi lower
	[GK_X_U] = 0x03A7, // chi upper
	[GK_PS_L] = 0x03C8, // psi lower
	[GK_PS_U] = 0x03A8, // psi upper
	[GK_W_L] = 0x03C9, // omega lower
	[GK_W_U] = 0x03A9, // omega upper
	[GK_WS_L] = 0x1F60, // omega smooth lower
	[GK_WS_U] = 0x1F68, // omega smooth upper
	[GK_WSA_L] = 0x1F64, // omega smooth acute lower
	[GK_WSA_U] = 0x1F6C, // omega smooth acute upper
	[GK_WSAI_L] = 0x1FA4, // omega smooth acute iota lower
	[GK_WSAI_U] = 0x1FAC, // omega smooth acute iota upper
	[GK_WSG_L] = 0x1F62, // omega smooth grave lower
	[GK_WSG_U] = 0x1F6A, // omega smooth grave upper
	[GK_WSGI_L] = 0x1FA2, // omega smooth grave iota lower
	[GK_WSGI_U] = 0x1FAA, // omega smooth grave iota upper
	[GK_WSC_L] = 0x1F66, // omega smooth circumflex lower
	[GK_WSC_U] = 0x1F6E, // omega smooth circumflex upper
	[GK_WSCI_L] = 0x1FA6, // omega smooth circumflex iota lower
	[GK_WSCI_U] = 0x1FAE, // omega smooth circumflex iota upper
	[GK_WSI_L] = 0x1FA0, // omega smooth iota lower
	[GK_WSI_U] = 0x1FA8, // omega smooth iota upper
	[GK_WR_L] = 0x1F61, // omega rough lower
	[GK_WR_U] = 0x1F69, // omega rough upper
	[GK_WRA_L] = 0x1F65, // omega rough acute lower
	[GK_WRA_U] = 0x1F6D, // omega rough acute upper
	[GK_WRAI_L] = 0x1FA5, // omega rough acute iota lower
	[GK_WRAI_U] = 0x1FAD, // omega rough acute iota upper
	[GK_WRG_L] = 0x1F63, // omega rough grave lower
	[GK_WRG_U] = 0x1F6B, // omega rough grave upper
	[GK_WRGI_L] = 0x1FA3, // omega rough grave iota lower
	[GK_WRGI_U] = 0x1FAB, // omega rough grave iota upper
	[GK_WRC_L] = 0x1F67, // omega rough cirumflex lower
	[GK_WRC_U] = 0x1F6F, // omega rough cirumflex upper
	[GK_WRCI_L] = 0x1FA7, // omega rough cirumflex iota lower
	[GK_WRCI_U] = 0x1FAF, // omega rough cirumflex iota upper
	[GK_WRI_L] = 0x1FA1, // omega rough iota lower
	[GK_WRI_U] = 0x1FA9, // omega rough iota upper
	[GK_WA_L] = 0x03CE, // omega acute lower
	[GK_WA_U] = 0x038F, // omega acute upper
	[GK_WAI_L] = 0x1FF4, // omega acute iota lower
	[GK_WAI_U] = 0x1FF4, // omega acute iota upper
	[GK_WG_L] = 0x1F7C, // omega grave lower
	[GK_WG_U] = 0x1FFA, // omega grave upper
	[GK_WGI_L] = 0x1FF2, // omega grave iota lower
	[GK_WGI_U] = 0x1FF2, // omega grave iota upper
	[GK_WC_L] = 0x1FF6, // omega circumflex lower
	[GK_WC_U] = 0x1FF6, // omega circumflex upper
	[GK_WCI_L] = 0x1FF7, // omega circumflex iota lower
	[GK_WCI_U] = 0x1FF7, // omega circumflex iota upper
	[GK_WCI_L] = 0x1FF3, // omega iota lower
	[GK_WCI_U] = 0x1FFC, // omega iota upper
	[GK_KO_L] = 0x03DF, // koppa lower
	[GK_KO_U] = 0x03DE, // koppa upper
	[GK_ST_L] = 0x03DB, // stigma lower
	[GK_ST_U] = 0x03DA, // stigma upper
	[GK_SP_L] = 0x03E1, // sampi lower
	[GK_SP_U] = 0x03E0, // sampi upper
};
