TAP_DANCE_ENABLE=yes
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
ENCODER_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_TRANSPORT = i2c
WPM_ENABLE = yes
LEADER_ENABLE = yes
UNICODEMAP_ENABLE = yes
AUTOCORRECT_ENABLE = yes

SRC += features/sentence_case.c
SRC += features/layer_lock.c
