TAP_DANCE_ENABLE=yes
REPEAT_KEY_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
ENCODER_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pmw3360
LEADER_ENABLE = yes
UNICODE_ENABLE = yes
UNICODEMAP_ENABLE = yes

SRC += features/sentence_case.c
